Feat: added contributing guidelines and fixed linting errors
FlowTestAI/FlowTest pull request #93
Opened 2024-05-03 19:04 UTC by xelacast

Updates issue #89 

[x] The PR title follows the conventions in [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
[x] Ran a functional test before committing

I added the CONTRIBUTING.md file to the root dir to walk through the contributions.
Fixed lining command issues for project in package.json ```pnpm``` lint and ```pnpm lint:fix``` and found unbreaking errors in many files.

This is still a work of progress and I don't know if we should use the changeset yet for versioning. I would appreciate feedback.

2024-05-04 00:46 UTC, jsajal requested changes
Left some comments but overall this is fantastic. 

Let me address some of the points that you raised

`linting errors` : yeah we are aware about them, I will find some time to fix those. Can you actually file an issue? that way it will be logged and it can be worked upon much faster.

> Offload changeset if applicable in the current timeframe

I think it's fine for now, if we see changelogs file increasing a lot we can always make more frequent minor releases (that deletes all changelog files till that point)

> [ ] - Create GitHub actions for linting and formatting checks for PRs
> [ ] - Create GitHub actions for build time errors

This is super helpful especially the second action about build and build time. I would prioritize that first.

2024-05-04 00:46 UTC, jsajal commented on .changeset/config.json
> +  "changelog": ["@changesets/cli/changelog", { "repo": "FlowTestAi/FlowTest" }],
nit: `FlowTestAi/FlowTest` -> `FlowTestAI/FlowTest`

2024-05-04 00:46 UTC, jsajal commented on CONTRIBUTING.md
> +If your change should appear in the changelog, i.e. it changes some behavior of either the CLI or the outputted application, it must be captured by `changeset` which is done by running
`outputted` -> `electron`

also can add a line for case when contributor does not want the hassle of changelog
`....If not then skip to the pr creation step`

2024-05-04 00:46 UTC, jsajal commented on package.json
> +    "clean": "rm -rf node_modules/ && rm -rf packages/flowtest-electron/node_modules/ && rm -rf packages/flowtest-cli"
I think you mean `rm -rf packages/flowtest-cli/node_modules/`

we don't want to clean the cli itself 😄

2024-05-04 16:21 UTC, xelacast commented on .changeset/config.json
> +  "changelog": ["@changesets/cli/changelog", { "repo": "FlowTestAi/FlowTest" }],
Good catch

2024-05-04 16:34 UTC, xelacast commented on CONTRIBUTING.md
Make sure to add a brief description about the eco system

2024-05-04 16:36 UTC, jsajal commented on CONTRIBUTING.md
oh yeah, i forgot to mention that in the comments, yes i will add and merge the PR later this weekend

2024-05-04 16:43 UTC, xelacast commented on CONTRIBUTING.md
Sick! That comment was meant for me lol. I was going to add a brief description of what the folders are doing/holding but you would be more equipped for that task.

2024-05-07 02:27 UTC, jsajal approved these changes

2024-05-07 02:27 UTC, merged